version: '3.9'

services:
  # Mongodb service
  mongo:
    container_name: db_container
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 8080:8080
    env_file: ./.env
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      BASE_URL: ${BASE_URL}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      PASSWORD_ENCRYPTION_KEY: ${PASSWORD_ENCRYPTION_KEY}
      MONGO_URI: ${MONGO_URI}
    depends_on: 
      - mongo

volumes:
  mongo_data: {}